"""Adjusts fks

Revision ID: 08835f36df1f
Revises: 01e7c0ce0a43
Create Date: 2022-09-14 22:50:24.099988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '08835f36df1f'
down_revision = '01e7c0ce0a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', postgresql.ENUM(name='state', create_type=False), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('complement', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providers_address')
    # ### end Alembic commands ###
