"""Add email field in employee table

Revision ID: 5456608e9751
Revises: a3af9eb576d5
Create Date: 2022-08-27 01:02:59.835362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5456608e9751'
down_revision = 'a3af9eb576d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
