"""Add table to employees and phone employees

Revision ID: a3af9eb576d5
Revises: 94bf0d6fed73
Create Date: 2022-08-26 21:44:12.134113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3af9eb576d5'
down_revision = '94bf0d6fed73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('keycloak_uuid', sa.String(length=37), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('employees_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('Cell', 'Telephone', name='PhoneTypesEmployees'), nullable=True),
    sa.Column('number', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('employees_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employees_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_phones')
    op.drop_table('employees')
    # ### end Alembic commands ###
