"""Ajudst fk in product table

Revision ID: e9239a2162fd
Revises: cfba01030dc4
Create Date: 2022-10-03 20:27:16.661023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9239a2162fd'
down_revision = 'cfba01030dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_category_id_fkey', 'products', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
